# Generated by Django 5.1.3 on 2024-12-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar_payment', '0003_orderproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProducts',
        ),
    ]
