# Generated by Django 5.1.3 on 2024-12-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_payment', '0006_ordersummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ordersummary',
            name='order_products',
        ),
        migrations.RemoveField(
            model_name='ordersummary',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
