# Generated by Django 5.1.3 on 2024-12-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_payment', '0007_remove_ordersummary_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('shipping_info', models.JSONField()),
                ('order_products', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderSummary',
        ),
    ]
