# Generated by Django 5.1.3 on 2024-12-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_payment', '0009_rename_ordersummarys_ordersummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='is_shipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
