# Generated by Django 5.1.3 on 2024-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_payment', '0010_ordersummary_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='orderd_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
