# Generated by Django 5.1.3 on 2024-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_payment', '0012_ordersummary_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='orderd_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
