# Generated by Django 5.1.3 on 2024-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_payment', '0014_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='India', max_length=255),
        ),
    ]
