# Generated by Django 5.1.3 on 2024-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productregistration',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
