# Generated by Django 5.1.3 on 2024-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0002_alter_productregistration_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners')),
            ],
        ),
        migrations.AlterField(
            model_name='productregistration',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
