# Generated by Django 5.1.3 on 2024-12-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0003_banners_alter_productregistration_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
