# Generated by Django 5.1.3 on 2024-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0004_delete_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistration',
            name='health_benefits',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productregistration',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
