# Generated by Django 5.1.3 on 2024-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0005_productregistration_health_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistration',
            name='second_image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='third_image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
