# Generated by Django 5.1.3 on 2024-12-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0006_productregistration_second_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistration',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
