# Generated by Django 5.1.3 on 2024-12-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0007_productregistration_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productregistration',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
