# Generated by Django 5.1.3 on 2024-12-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregistration',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='third_image',
        ),
    ]
