# Generated by Django 5.1.3 on 2024-12-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0011_contact_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
