# Generated by Django 5.1.3 on 2024-12-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar_store', '0013_region_subregion_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subregion',
            name='region',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='SubRegion',
        ),
    ]
